language: go
go:
  - "1.12.x"
os:
  # - linux
  # - osx
  - windows
addons:
  homebrew:
    packages:
    - gnupg
    - pass
  apt:
    packages:
    - pass
env:
  - GO111MODULE=on
script:
  - diff -u <(echo -n) <(gofmt -d $(git ls-files '*.go'))
  - go vet ./...
  - go test -race ./...
