language: go

before_install:
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get install pass; else brew install pass; fi

install:
  - go get github.com/kardianos/govendor
  - govendor status

go:
  - 1.8
  - 1.9

os:
  - linux
  - osx

osx_image: xcode7.3
