language: go
go:
  - "1.12.x"
os:
  - linux
  - osx
addons:
  homebrew:
    update: True
    packages:
    - gnupg
    - pass
  apt:
    packages:
    - pass

script:
  - diff -u <(echo -n) <(gofmt -d $(git ls-files '*.go'))
  - go vet ./...
  - go test -race ./...
