language: go

before_install:
  - go get -u github.com/kardianos/govendor
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
        brew update;
        brew install gnu-getopt;
        brew upgrade gnupg;
    fi
  - wget https://git.zx2c4.com/password-store/snapshot/password-store-1.7.1.tar.xz
  - tar -xJvf password-store-1.7.1.tar.xz
  - pushd password-store-1.7.1 && sudo make install PREFIX=/usr/local && popd

install:
  - go get github.com/kardianos/govendor
  - govendor status

go:
  - "1.10.x"
  - "1.11.x"

os:
  - linux
  - osx

script:
  - govendor status
  - diff -u <(echo -n) <(gofmt -d $(git ls-files '*.go' | grep -v ^vendor/))
  - go vet ./...
  - go test -race ./...
