name: Continuous Integration
on: push

jobs:

  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - run: sudo apt-get install pass gnome-keyring dbus-x11
      - uses: actions/checkout@v1
      - run: go test -race ./...
      - run: go vet ./...

  mac:
    runs-on: macOS-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - run: brew install pass gnupg
      - uses: actions/checkout@v1
      - run: go test -race ./...
      - run: go vet ./...

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - uses: actions/checkout@v1
      - run: diff -u <(echo -n) <(gofmt -s -d .)
